package uk.gov.justice.digital.hmpps.hmppsassessforearlyreleaseapi.resource.enum

enum class DocumentSubjectType {
  OFFENDER_ELIGIBLE_FORM,
  OFFENDER_ADDRESS_CHECKS_INFORMATION_FORM,
  OFFENDER_ADDRESS_CHECKS_FORM,
  OFFENDER_OPT_OUT_FORM,
  OFFENDER_NOT_ELIGIBLE_FORM,
  OFFENDER_NOT_SUITABLE_FORM,
  OFFENDER_ADDRESS_UNSUITABLE_FORM,
  OFFENDER_POSTPONED_FORM,
  OFFENDER_NOT_ENOUGH_TIME_FORM,
  OFFENDER_APPROVED_FORM,
  OFFENDER_AGENCY_NOTIFICATION_FORM,
  OFFENDER_CANCEL_AGENCY_NOTIFICATION_FORM,
  OFFENDER_REFUSED_FORM,
}
