services:
  afer-test-db:
    image: postgres:16.3
    networks:
      - hmpps-test
    container_name: afer-test-db
    user: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=afer-test-db
      - POSTGRES_USER=afer
      - POSTGRES_PASSWORD=dummy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d afer-test-db -U afer" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - test-pgdata:/var/lib/postgresql/data

  gotenberg:
    image: gotenberg/gotenberg:8.0.0
    networks:
      - hmpps
    container_name: gotenberg
    ports:
      - "3002:3000"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  test-pgdata:

networks:
  hmpps-test:
