version: "3"
services:
  afer-db:
    image: postgres:16.3
    networks:
      - hmpps
    container_name: afer-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=afer
      - POSTGRES_USER=afer
      - POSTGRES_DB=assess-for-early-release-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d create-and-vary-a-licence-db -U cvl" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  hmpps:
