services:
  afer-db:
    image: postgres:16.3
    networks:
      - hmpps
    container_name: afer-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=root
      - POSTGRES_DB=assess-for-early-release-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d assess-for-early-release-db -U afer" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  localstack-afer-api:
    image: localstack/localstack:3.6
    networks:
      - hmpps
    container_name: localstack-afer-api
    ports:
      - "4666:4666"
      - "4610-4659:4610-4659"
    environment:
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - GATEWAY_LISTEN=0.0.0.0:4666
      - EXTERNAL_SERVICE_PORTS_START=4610
      - EXTERNAL_SERVICE_PORTS_END=4659
      - MAIN_CONTAINER_NAME=hmpps-assess-for-early-release-api
      - AWS_ENDPOINT_URL=http://localhost:4666
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: awslocal sqs list-queues
      interval: 10s
      timeout: 5s
      retries: 5

  gotenberg:
    image: gotenberg/gotenberg:8.0.0
    networks:
      - hmpps
    container_name: gotenberg
    ports:
      - "3002:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:

networks:
  hmpps:
