#
# The dev profile is for running the API service locally against a postgres database (5432).
#
spring:
  jpa:
    show-sql: true

hmpps:
  prisonersearch:
    api:
      url: "https://prisoner-search-dev.prison.service.justice.gov.uk"
  prisonregister:
    api:
      url: "https://prison-register-dev.hmpps.service.justice.gov.uk"
hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4666
  queues:
    domaineventsqueue:
      queueName: domainevents-queue
      dlqName: domainevents-queue-dlq
      subscribeTopicId: domainevents
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:domainevents-topic

os:
  places:
    api:
      url: "https://api.os.uk/search/places/v1"

