#
# The dev profile is for running the API service locally against a postgres database (5432).
#
spring:

  jpa:
    show-sql: true

hmpps:
  auth:
    token:
      url: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/token"
  delius:
    api:
      url: "https://assess-for-early-release-and-delius-dev.hmpps.service.justice.gov.uk"
  prisonersearch:
    api:
      url: "https://prisoner-search-dev.prison.service.justice.gov.uk"
  prisonregister:
    api:
      url: "https://prison-register-dev.hmpps.service.justice.gov.uk"
  probationsearch:
    api:
      url: "https://probation-offender-search-dev.hmpps.service.justice.gov.uk"

gotenberg:
  api:
    url: "http://hmpps-assess-for-early-release-gotenberg"

assessments:
    url: "https://assess-for-early-release-dev.hmpps.service.justice.gov.uk"

hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4666
  queues:
    domaineventsqueue:
      queueName: domainevents-queue
      dlqName: domainevents-queue-dlq
      subscribeTopicId: domainevents
    hmppsoffenderqueue:
      queueName: hmppsoffender-queue
      dlqName: hmppsoffender-queue-dlq
      subscribeTopicId: hmppsoffender
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:domainevents-topic
    hmppsoffender:
      arn: arn:aws:sns:eu-west-2:000000000000:hmppsoffender-topic
