---
# Per environment values which override defaults in hmpps-assess-for-early-release-api/values.yaml

generic-service:
  ingress:
    host: assess-for-early-release-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    HMPPS_AUTH_TOKEN_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth/oauth/token"
    HMPPS_DELIUS_API_URL: "https://assess-for-early-release-and-delius-dev.hmpps.service.justice.gov.uk"
    HMPPS_PRISONERSEARCH_API_URL: "https://prisoner-search.prison.service.justice.gov.uk"
    HMPPS_PRISONREGISTER_API_URL: "https://prison-register.hmpps.service.justice.gov.uk"
    HMPPS_PROBATIONSEARCH_API_URL: "https://probation-offender-search.hmpps.service.justice.gov.uk"
    OS_PLACES_API_URL: "https://api.os.uk/search/places/v1"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: cvl_alerts
