package uk.gov.justice.digital.hmpps.hmppsassessforearlyreleaseapi.entity

enum class Task {
  ASSESS_ELIGIBILITY,
  ENTER_CURFEW_ADDRESS,
  COMPLETE_PRE_RELEASE_CHECKS,
  REVIEW_APPLICATION_AND_SEND_FOR_DECISION,
  COMPLETE_14_DAY_CHECKS,
  COMPLETE_2_DAY_CHECKS,
  PRINT_LICENCE,

  CONSULT_THE_VLO_AND_POM,
  CHECK_ADDRESSES_OR_COMMUNITY_ACCOMMODATION,
  MAKE_A_RISK_MANAGEMENT_DECISION,
  SEND_CHECKS_TO_PRISON,
  CREATE_LICENCE,

  CONFIRM_RELEASE,
  APPROVE_LICENCE,
  OPT_IN,
}

enum class TaskStatus {
  LOCKED,
  READY_TO_START,
  IN_PROGRESS,
  COMPLETE,
}
